# Generated by Django 3.1.2 on 2021-04-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210402_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language_name',
            new_name='name',
        ),
    ]
